{% set version = "0.3.8" %}

package:
  name: ecmwf-opendata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/ecmwf-opendata/ecmwf-opendata-{{ version }}.tar.gz
  sha256: 8a9c29ba369088477f9db2a2dabdb8f5282f02f6756e83d4288b38ed4d663c29

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - multiurl >=0.2.1

test:
  imports:
    - ecmwf.opendata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf/ecmwf-opendata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download ECMWF open data

extra:
  recipe-maintainers:
    - raybellwaves
