{% set version = "0.3.14" %}

package:
  name: ecmwf-opendata
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/ecmwf-opendata/ecmwf-opendata-{{ version }}.tar.gz
  sha256: f0704720902103f10d406183a1251754a345c071378681c3171b4c44aad7428a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - multiurl >=0.2.1

test:
  imports:
    - ecmwf.opendata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ecmwf/ecmwf-opendata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download ECMWF open data

extra:
  recipe-maintainers:
    - raybellwaves
