{% set version = "0.3.22" %}

package:
  name: ecmwf-opendata
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/ecmwf-opendata/ecmwf_opendata-{{ version }}.tar.gz
  sha256: 480628068dddeefb6774d9576f2cce8d9dff491dcde4832d8e6777b8b8f3549f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - multiurl >=0.2.1

test:
  imports:
    - ecmwf.opendata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ecmwf/ecmwf-opendata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download ECMWF open data

extra:
  recipe-maintainers:
    - raybellwaves
