{% set version = "0.2.0" %}

package:
  name: ecmwf-opendata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/ecmwf-opendata/ecmwf-opendata-{{ version }}.tar.gz
  sha256: 628891bd72af645616c257ca02d79e8a22baa12f49865d78d23b6459ce0ab056

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - multiurl

test:
  imports:
    - ecmwf.opendata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf/ecmwf-opendata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download ECMWF open data

extra:
  recipe-maintainers:
    - raybellwaves
