{% set version = "0.3.3" %}

package:
  name: ecmwf-opendata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/ecmwf-opendata/ecmwf-opendata-{{ version }}.tar.gz
  sha256: 6f3181c7872b72e5529d2b4b7ec6ff08d37c37beee0a498f7f286410be178c6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - multiurl

test:
  imports:
    - ecmwf.opendata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf/ecmwf-opendata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download ECMWF open data

extra:
  recipe-maintainers:
    - raybellwaves
