{% set version = "0.3.10" %}

package:
  name: ecmwf-opendata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/ecmwf-opendata/ecmwf-opendata-{{ version }}.tar.gz
  sha256: 7bc417f02f4f04b2ab1e4e98508b7c4ce5f5a0ca2bc82317a1a861f20aa54af4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - multiurl >=0.2.1

test:
  imports:
    - ecmwf.opendata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf/ecmwf-opendata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download ECMWF open data

extra:
  recipe-maintainers:
    - raybellwaves
